name: ff_pockedex
description: "A Pokemon encyclopedia app built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Network
  dio: ^5.4.0

  # State management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Local database
  sqflite: ^2.3.0
  path: ^1.8.3

  # Image caching
  cached_network_image: ^3.3.1

  # Color extraction from images
  palette_generator: ^0.3.3+3

  # Animations
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8

flutter:
  uses-material-design: true